GET http://localhost:5159/users/8d2832b0-93b8-42c5-8153-aa4145ede53d

###
POST http://localhost:5159/users/register
Content-Type: application/json

{
    "authId": "8d5832b0-93b8-42c5-8153-aa4145ede53d",
    "username": "mango",
    "email": "mango@gmail.com",
    "sqAnswer": "flowers"
}

###
POST http://localhost:5159/users/forgotPassword
Content-Type: application/json

{
    "email": "coco@gmail.com",
    "sqAnswer": "mango"
}

###
DELETE http://localhost:5159/users/8d2832b0-93b8-42c5-8153-aa4145ede53d/delete


###
GET http://localhost:5159/users/8d2832b0-93b8-42c5-8153-aa4145ede53d/profiles

###
POST http://localhost:5159/users/4/profiles/create
Content-Type: application/json

{
    "userId": 4,
    "backgroundColor": "none",
    "animationType": "animationOne"
}

###
PUT http://localhost:5159/users/8d2832b0-93b8-42c5-8153-aa4145ede53d/profiles/update
Content-Type: application/json

{
    "animationType": "animationTwo"
}